# Generated by Django 5.2.13 on 2026-04-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0002_skill_auditlog_details_dependency_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('channel_link', models.URLField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='sky.team')),
            ],
        ),
    ]
